### ISSUE TITLE
Verify eth proof failed in mintable-fungible-token contract

### ISSUE THREAD

**Issue by ailisp** [near/rainbow-bridge-cli#256]
As reported by @Kouprin 
```
Mint failed with error:
Error: {"ActionError":{"index":0,"kind":{"FunctionCallError":{"HostError":{"GuestPanic":{"panic_msg":"panicked at 'Failed to verify the proof', mintable-fungible-token/src/lib.rs:450:9"}}}}}}
    at signAndSendTransaction (/Users/kpr/near/rainbow-bridge/environment/lib/borsh/index.js:308:11)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async NearMintableToken.value [as mint] (/Users/kpr/near/rainbow-bridge/environment/lib/borsh/index.js:340:39)
    at async Function.mint (/Users/kpr/near/rainbow-bridge/environment/commands/transfer-eth-erc20-to-near.js:144:13)
    at async Command.execute (/Users/kpr/near/rainbow-bridge/environment/commands/transfer-eth-erc20-to-near.js:271:13)
    at async Promise.all (index 0)
    at async /Users/kpr/near/rainbow-bridge/environment/index.js:467:16
```
when run e2e test. However logs of eth-relay and near-relay looks good. It's reproducible to @Kouprin everytime but not reproducible to me.

**Comment by Kouprin** [comment]
Tested nodejs version difference (12 vs 13) and rustc version (1.44.1 vs 1.45.1). No progress.

**Comment by nearmax** [comment]
There is some unknown here. Setting estimate to 3.

**Comment by Kouprin** [comment]
Resolved. The issue was in difference in yarn versions (1.22.0 vs 1.22.4).
