### ISSUE TITLE
Unclear how to use eth-dump

### ISSUE THREAD

**Issue by alexfmpe** [near/rainbow-bridge-cli#371]
I launched a go-ethereum node locally and `eth-dump` seems to get the block count correctly but errors immediately after.

```
$ yarn install

$ ./index.js eth-dump --eth-node-url http://localhost:8545 headers
Downloading block 11 down to 0 to undefined. 12 blocks in total.
Downloading block 11
Processing block 11
(node:7370) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Function.dumpHeaders (rainbow-bridge-cli/commands/eth-dump.js:69:24)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Command.execute (rainbow-bridge-cli/commands/eth-dump.js:46:9)
    at async Promise.all (index 0)
    at async rainbow-bridge-cli/index.js:634:3
(node:7370) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:7370) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

$ ./index.js eth-dump --eth-node-url http://localhost:8545 proofs 
Downloading block 11 down to 0 to undefined. 12 blocks in total.
(node:2961) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'close' of undefined
    at EthProofExtractor.destroy (rainbow-bridge-cli/node_modules/rainbow-bridge-lib/eth-proof-extractor/index.js:63:46)
    at Command.execute (rainbow-bridge-cli/commands/eth-dump.js:56:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Promise.all (index 0)
    at async rainbow-bridge-cli/index.js:634:3
(node:2961) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2961) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by djsatok** [comment]
@alexfmpe can you please elaborate on the bug? What was the use case for `eth-dump`?
